# MPI-based makefile using mpic++ and mpicc

MR_INC = ../LIBs/mrmpi-7Apr14/src/ 
MR_LIB = ../LIBs/mrmpi-7Apr14/src/libmrmpi_mpicc.a 

Zlib_INC = ../LIBs/ZLIB/include/ 
Zlib_LIB = ../LIBs/ZLIB/lib/libz.a 

CC =		mpicxx
CXX =		mpicxx 
CCFLAGS =	-std=c++0x -m64 -g -O2 -Wno-deprecated -I$(MR_INC) -I$(Zlib_INC)
LINK =		mpicxx
LINKFLAGS =	-std=c++0x -m64 -g -O2 -Wno-deprecated 
USRLIB_0 =	$(MR_LIB) 
USRLIB_1 = 	$(Zlib_LIB) 
USRLIB_2 =	
USRLIB_3 =	
USRLIB_4 = 
SYSLIB =

include Makefile.common
